# Generated by Django 5.2 on 2025-04-12 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='data_exports/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', 'Yakunlandi'), ('failed', 'Xatolik')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Ma'lumotlar eksporti",
                'verbose_name_plural': "Ma'lumotlar eksportlari",
                'ordering': ['-created_at'],
            },
        ),
    ]
