# Generated by Django 5.2 on 2025-04-12 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pressure', models.DecimalField(decimal_places=2, max_digits=6)),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wind_direction', models.CharField(max_length=3)),
                ('precipitation', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='station.station')),
            ],
            options={
                'verbose_name': "Ob-havo ma'lumoti",
                'verbose_name_plural': "Ob-havo ma'lumotlari",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['station', 'timestamp'], name='weather_wea_station_c0c03b_idx')],
            },
        ),
    ]
