# Generated by Django 5.2 on 2025-04-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='wind_direction',
            field=models.CharField(max_length=10),
        ),
    ]
