# Generated by Django 5.2 on 2025-04-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_station_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='elevation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
